### ISSUE TITLE
New regret screen

### ISSUE THREAD

**Issue by gregcodethem** [gregcodethem/choices_behind_doors_study#24]
After switch/stick and before getting your answer (lose or win) in the Monty Hall game, there will be a question, what extent would you feel regret if you lose.

With options of 1 to 7.

**Comment by medialucida** [comment]
One version will be this.  the other version will be randomised
, but I do not know how to randomised yet.  In each condition (low, medium, high), there will be 50 participants.  25 of them will be given this version and the other 25 will be given randomised version.

**Comment by gregcodethem** [comment]
Half will be 1 to 7, the other half will be 7 to 1.

**Comment by medialucida** [comment]
yes, both will say 1= not at all 7= extremely

________________________________

**Comment by gregcodethem** [comment]
The wiring is working so that this site now links to the next page, I just need to get it to display the numbers and save them, also creating the models etc

**Comment by gregcodethem** [comment]
Have created model, now to look at other survey questions for the right form, or closest to it.

**Comment by gregcodethem** [comment]
First will get them to just save properly, then will work on getting the display.

**Comment by gregcodethem** [comment]
Saving properly.  Next work on the display, then the two options for the order of the numbers.
